#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 testing.'

# Check Prettier standards
#npm run check-format ||
#(
#    echo '🤢🤮🤢🤮 Check-format failed 🤢🤮🤢🤮
#            Prettier Check Failed. Run npm run format, add changes and try commit again.';
#    false;
#)

# Check ESLint Standards
npm run check-lint ||
(
        echo '😤🏀👋😤 Check-lint failed 😤🏀👋😤 
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
# npm run check-types ||
# (
#     echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡'
#     false;
# )

# If everything passes... Now we can commit
echo 'I am committing this now. ✅'

